# language: java
# jdk:
#   - oraclejdk8

# install:
#   - mvn install -DskipTests=false -B -V

# before_deploy:
#   - mvn package
#   - cd build
#   - zip -r UFM-Reckoning ./* -x ./maven-archiver\* ./maven-status\* ./classes\* ./surefire-reports\* ./test-classes\* ./generated-sources\* ./generated-test-sources\* ./generated-classes\* ./cobertura\* ./testtarget\*
#   - ls
#   - cd ..

# deploy:
#   provider: releases
#   api-key: "1e012471263182440d6f62b82a99e8d63df0dd5e"
#   file: "./build/UFM-Reckoning.zip"
#   skip_cleanup: true
#   on:
#     tags: true
#     all_branches: true
#     jdk: oraclejdk8

# notifications:
#   email:
#     recipients:
#       - joshua.b.slik@gmail.com
#       - sabenoist5@gmail.com
#       - naomi-ah@hotmail.com
#       - bryanvanwijk@hotmail.com
#       - lisette_stella@hotmail.com
#     on_success: change
#     on_failure: always